biru/urls.py
from django.urls import path

from . import views

app_name = 'biru'

urlpatterns = [
    path('', views.home, name='home'),
    path('qstaff', views.qstaff, name='qstaff'),
    path('qpelanggan', views.qpelanggan, name='qpelanggan'),
    path('qkurir', views.qkurir, name='qkurir'),
    path('staff', views.staff, name='staff'),
    path('update', views.update, name='update'),
    path('delete', views.delete, name='delete'),
    path('kurir', views.kurir, name='kurir'),
    path('create', views.create, name='create'),
    path('status', views.status, name='status'),
    path('pilih', views.pilihEmail, name='pilih'),
]

merah/urls.py
from django.urls import path

from . import views

app_name = 'merah'

urlpatterns = [
    path('', views.home, name='home'),
    path('testimoni/rud', views.rud_testimoni, name='rud_testimoni'),
    path('layanan/ru', views.ru_layanan, name='ru_layanan'),
    path('testimoni/create', views.createtestimoni, name='createtestimoni'),
    path('testimoni/update', views.updatetestimoni, name='updatetestimoni'),
    path('layanan/update', views.updatelayanan, name='updatelayanan'),
]

project_tk2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('merah/', include('merah.urls')),
    path('kuning/', include('kuning.urls')),
    path('hijau/', include('hijau.urls')),
    path('biru/', include('biru.urls')),
]

merah/models.py
from django.db import models

# Create your models here.

merah/views.py
from django.shortcuts import render
from django.shortcuts import redirect

# Create your views here.
def home(request):
    return render(request, 'fiturmerah.html')

def createtestimoni(request):
    return render(request, 'createtestimoni.html')

def ru_layanan(request):
    return render(request, 'ru_layanan.html')

def rud_testimoni(request):
    return render(request, 'rud_testimoni.html')

def updatelayanan(request):
    return render(request, 'updatelayanan.html')

def updatetestimoni(request):
    return render(request, 'updatetestimoni.html')

merah/templates/createtestimoni.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Testimoni</title>
</head>
<body>
    <h1>
        FORM TESTIMONI
    </h1>
    <div class = ctestimoni>
        <form id = ctestimoni>
            <label for="email">Email:</label><br>
            <input type="text" id="email" name="email"><br>
            <label for="tanggal_transaksi">Tanggal Transaksi:</label><br>
            <input type="text" id="tanggal_transaksi" name="tanggal_transaksi"><br>
            <label for="status">Status:</label><br>
            <input type="text" id="status" name="status"><br>
            <label for="rating">Rating:</label><br>
            <input type="text" id="rating" name="rating"><br>
        </form>
        <button class="button" type="submit">SUBMIT</button>
    </div>
</body>
</html>

merah/templates/fiturmerah.html
<!DOCTYPE html>
<html>
<head>
    <title>FITUR MERAH</title>
</head>
<body>
    <h1>
        CREATE, READ, UPDATE, DELETE TESTIMONI & READ, UPDATE, DELETE LAYANAN
    </h1>
    <div class = fiturmerah>
        <button>
            <a href="{% url 'merah:createtestimoni' %}">BUAT TESTIMONI</a>
        </button>
        <button>
            <a href="{% url 'merah:rud_testimoni' %}">TESTIMONI</a>
        </button>
        <button>
            <a href="{% url 'merah:ru_layanan' %}">LAYANAN</a>
        </button>
    </div>
</body>
</html>

merah/templates/ru_layanan.html
<!DOCTYPE html>
<html>
<head>
    <title>Layanan</title>
</head>
<body>
    <h1>
        LAYANAN
    </h1>
    <div class = rulayanan>
        <table>
            <caption>DAFTAR LAYANAN SILAU</caption>
            <thead>
                <tr>
                    <th><b>Kode Layanan</b></th>
                    <th><b>Nama Layanan</b></th>
                    <th><b>Durasi (menit)</b></th>
                    <th><b>Harga (per kg)</b></th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>RG</td>
                    <td>Regular</td>
                    <td>2 hari</td>
                    <td>10000</td>
                    <td>
                        <button>
                            <a href="{% url 'merah:updatelayanan' %}">UPDATE</a>
                        </button>
                    </td>
                </tr>
                <tr>
                    <td>EX</td>
                    <td>Express</td>
                    <td>1 hari</td>
                    <td>15000</td>
                    <td>
                        <button>
                            <a href="{% url 'merah:updatelayanan' %}">UPDATE</a>
                        </button>
                    </td>
                </tr>
                <tr>
                    <td>SE</td>
                    <td>Super Express</td>
                    <td>3 jam</td>
                    <td>20000</td>
                    <td>
                        <button>
                            <a href="{% url 'merah:updatelayanan' %}">UPDATE</a>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>

merah/templates/rud_testimoni.html
<!DOCTYPE html>
<html>
<head>
    <title>Testimoni</title>
</head>
<body>
    <h1>
        TESTIMONI
    </h1>
    <div class = rudtestimoni>
        <table>
            <caption>DAFTAR TESTIMONI SILAU</caption>
            <thead>
                <tr>
                    <th><b>Email</b></th>
                    <th><b>Tanggal Transaksi</b></th>
                    <th><b>Tanggal Testimoni</b></th>
                    <th><b>Status</b></th>
                    <th><b>Rating</b></th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>joffill0@photobucket.com</td>
                    <td>2020-10-31 14:07:55</td>
                    <td>2020-11-20 10:44:09</td>
                    <td>Layanan bagus!</td>
                    <td>4</td>
                    <td>
                        <button>
                            <a href="{% url 'merah:updatetestimoni' %}">UPDATE</a>
                        </button>
                        <button>
                            <a href="">DELETE</a>
                        </button>
                    </td>
                </tr>
                <tr>
                    <td>momrod1@hibu.com</td>
                    <td>2020-10-31 07:08:22</td>
                    <td>2020-11-22 20:11:14</td>
                    <td>puas dengan servisnya. Besok-besok laundry di silau lagi</td>
                    <td>5</td>
                    <td>
                        <button>
                            <a href="{% url 'merah:updatetestimoni' %}">UPDATE</a>
                        </button>
                        <button>
                            <a href="">DELETE</a>
                        </button>
                    </td>
                </tr>
                <tr>
                    <td>mwelfair2@ucla.edu</td>
                    <td>2020-11-03 08:29:13</td>
                    <td>2020-11-23 01:04:11</td>
                    <td></td>
                    <td>2</td>
                    <td>
                        <button>
                            <a href="{% url 'merah:updatetestimoni' %}">UPDATE</a>
                        </button>
                        <button>
                            <a href="">DELETE</a>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>

merah/templates/updatelayanan.html
<!DOCTYPE html>
<html>
<head>
    <title>Update Layanan</title>
</head>
<body>
    <h1>
        FORM UPDATE LAYANAN
    </h1>
    <div class = ulayanan>
        <form id = ulayanan>
            <label for="kode_layanan">Kode Layanan:</label><br>
            <input type="text" id="kode_layanan" name="kode_layanan"><br>
            <label for="nama_layanan">Nama Layanan:</label><br>
            <input type="text" id="nama_layanan" name="nama_layanan"><br>
            <label for="durasi">Durasi:</label><br>
            <input type="text" id="durasi" name="durasi"><br>
            <label for="harga">Harga (per kg):</label><br>
            <input type="text" id="harga" name="harga"><br>
        </form>
        <button class="button" type="submit">UPDATE</button>
    </div>
</body>
</html>

merah/templates/updatetestimoni.html
<!DOCTYPE html>
<html>
<head>
    <title>Update Testimoni</title>
</head>
<body>
    <h1>
        FORM UPDATE TESTIMONI
    </h1>
    <div class = utestimoni>
        <form id = utestimoni>
            <label for="email">Email:</label><br>
            <input type="text" id="email" name="email"><br>
            <label for="tanggal_transaksi">Tanggal Transaksi:</label><br>
            <input type="text" id="tanggal_transaksi" name="tanggal_transaksi"><br>
            <label for="status">Status:</label><br>
            <input type="text" id="status" name="status"><br>
            <label for="rating">Rating:</label><br>
            <input type="text" id="rating" name="rating"><br>
        </form>
        <button class="button" type="submit">UPDATE</button>
    </div>
</body>
</html>