biru/urls.py
from django.urls import path

from . import views

app_name = 'biru'

urlpatterns = [
    path('', views.home, name='home'),
    path('qstaff', views.qstaff, name='qstaff'),
    path('qpelanggan', views.qpelanggan, name='qpelanggan'),
    path('qkurir', views.qkurir, name='qkurir'),
    path('staff', views.staff, name='staff'),
    path('update', views.update, name='update'),
    path('delete', views.delete, name='delete'),
    path('kurir', views.kurir, name='kurir'),
    path('create', views.create, name='create'),
    path('status', views.status, name='status'),
    path('pilih', views.pilihEmail, name='pilih'),
]

project_tk2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('merah/', include('merah.urls')),
    path('kuning/', include('kuning.urls')),
    path('hijau/', include('hijau.urls')),
    path('biru/', include('biru.urls')),
]

biru/models.py
from django.db import models

# Create your models here.

biru/views.py
from django.shortcuts import render, redirect
from django.db import connection
from datetime import datetime

# Create your views here.
def home(request):
    return render(request, 'biru.html')

def qkurir(request):
    return render(request, 'birukurir.html')

def qstaff(request):
    return render(request, 'birustaff.html')

def qpelanggan(request):
    return render(request, 'birupelanggan.html')

def staff(request):
    if 'is_login' in request.session:
        if request.session['user_type'] == 'Pelanggan':
            email = request.session['email']
            query = f"select * from transaksi_topup_dpay where email = '{email}'"
            with connection.cursor() as cursor:
                cursor.execute(query)
                dummy = cursor.fetchall()
        else:
            with connection.cursor() as cursor:
                cursor.execute('select * from transaksi_topup_dpay')
                dummy = cursor.fetchall()
    else:
        with connection.cursor() as cursor:
            cursor.execute('select * from transaksi_topup_dpay')
            dummy = cursor.fetchall()
    context = {
        'dummy' : dummy
    }
    return render(request, 'staff.html', context)

def kurir(request):
    with connection.cursor() as cursor:
        cursor.execute('select * from transaksi_topup_dpay')
        dummy = cursor.fetchall()
    context = {
        'dummy' : dummy
    }
    return render(request, 'kurir.html', context)

def pilihEmail(request):
    if request.method == 'POST':
        with connection.cursor() as cursor:
            query = f"select * from transaksi_topup_dpay where email ='{request.POST['email']}'"
            cursor.execute(query)
            dummy = cursor.fetchall()
        context = {
            'dummy' : dummy
        }
        return render(request, 'staff.html', context)
    else:
        with connection.cursor() as cursor:
            cursor.execute('select email from transaksi_topup_dpay')
            dummy = cursor.fetchall()
        context = {
            'dummy' : dummy
        }
        return render(request, 'emailPengguna.html', context)

def delete(request):
    if request.method == 'POST':
        tgl = request.POST['tanggal']
        query = f"delete from transaksi_topup_dpay where tanggal='{tgl}'"
        with connection.cursor() as cursor:
            cursor.execute(query)
        return redirect('biru:staff')


def update(request):
    if request.method == 'POST':
        email = request.POST['email']
        tanggal = request.POST['date']
        nominal = request.POST['nominal']
        query = f"update transaksi_topup_dpay set nominal = {nominal}  where email = '{email}' and tanggal = '{tanggal}'";
        with connection.cursor() as cursor:
            cursor.execute(query)
    return redirect('biru:staff')


def create(request):
    if request.method == 'POST':
        now = datetime.now()
        dt_string = now.strftime("%Y-%m-%d %H:%M:%S")
        query = f"INSERT INTO transaksi_topup_dpay VALUES ('{request.POST['email']}','{dt_string}','{request.POST['nominal']}')"
        with connection.cursor() as cursor:
            cursor.execute(query)
            cursor.execute('select * from transaksi_topup_dpay')
            dummy = cursor.fetchall()
        context = {
            'dummy' : dummy
        }
        return render(request, 'staff.html', context)
    else:
        with connection.cursor() as cursor:
            cursor.execute('select email from transaksi_topup_dpay')
            dummy = cursor.fetchall()
        context = {
            'dummy' : dummy
        }
        return render(request, 'createTransaksi.html', context)

def status(request):
    with connection.cursor() as cursor:
        cursor.execute('select * from status')
        dummy = cursor.fetchall()
    context = {
        'dummy' : dummy
    }
    return render(request, 'status.html', context)

biru/templates/biru.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Fitur biru</title>
{% endblock meta %}


{% block content %}
    <div style="text-align: justify;"> 
        <h1>Silahkan pilih role anda</h1>
        <a href="{% url 'biru:qstaff' %}"><button  onclick="google.com">Staff</button></a>
        <a href="{% url 'biru:qpelanggan' %}"><button  onclick="google.com">Pelanggan</button></a>
        <a href="{% url 'biru:qkurir' %}"><button  onclick="google.com">Kurir</button></a>
    </div>
{% endblock content %}

biru/templates/birukurir.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Query kurir</title>
{% endblock meta %}


{% block content %}
    <div style="text-align: justify;"> 
        <h1>Silahkan pilih pilihan yang anda inginkan, kurir!</h1>
        <h3>Read Update Delete Transaksi TOPUP DPAY</h3>
        <a href="{% url 'biru:kurir' %}"><button  onclick="google.com">Click here! </button></a>
        <h3>Read Status</h3>
        <a href="{% url 'biru:status' %}"><button  onclick="google.com">Click here!</button></a>
        <h3>Go back</h3>
        <a href="{% url 'biru:home' %}"><button  onclick="google.com">Click here!</button></a>
    </div>
{% endblock content %}

biru/templates/birupelanggan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Query pelanggan</title>
{% endblock meta %}


{% block content %}
    <div style="text-align: justify;"> 
        <h1>Silahkan pilih pilihan yang anda inginkan, pelanggan!</h1>
        <h3>Read Update Delete Transaksi TOPUP DPAY</h3>
        <a href="{% url 'biru:pilih' %}"><button  onclick="google.com">Click here! </button></a>
        <h3>Read Status</h3>
        <a href="{% url 'biru:status' %}"><button  onclick="google.com">Click here!</button></a>
        <h3>Go back</h3>
        <a href="{% url 'biru:home' %}"><button  onclick="google.com">Click here!</button></a>
    </div>
{% endblock content %}

biru/templates/birustaff.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Query staff</title>
{% endblock meta %}


{% block content %}
    <div style="text-align: justify;"> 
        <h1>Silahkan pilih pilihan yang anda inginkan, staff!</h1>
        <h3>Read Update Delete Transaksi TOPUP DPAY</h3>
        <a href="{% url 'biru:staff' %}"><button  onclick="google.com">Click here! </button></a>
        <h3>Create Transaksi TOPUP DPAY</h3>
        <a href="{% url 'biru:create' %}"><button  onclick="google.com">Click here!</button></a>
        <h3>Read Status</h3>
        <a href="{% url 'biru:status' %}"><button  onclick="google.com">Click here!</button></a>
        <h3>Go back</h3>
        <a href="{% url 'biru:home' %}"><button  onclick="google.com">Click here!</button></a>
    </div>
{% endblock content %}

biru/templates/createTransaksi.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>CREATE TRANSAKSI TOPUP DPAY</title>
{% endblock meta %}

{% block content %}
    <div style="text-align: justify;"> 
        <h1>FORM CREATE TRANSAKSI TOPUP DPAY</h1>
            <form action="{% url 'biru:create' %}" method="POST">
                {% csrf_token %}
                <label for="fname">Email</label>
                <input type="text" name="email" id="cars" list="cityname">
                <datalist id="cityname">
                    {% for dum in dummy %}
                        <option value= {{ dum.0 }}>{{ dum.0 }}</option>
                    {% endfor %}
                </datalist>
                <label for="fname">Nominal</label>
                <input type="text" id="fname" name="nominal">
                <br>
                <br>
                <button type="submit" value="Submit">Submit</button>
            </form>
    </div>
{% endblock content %}

biru/templates/emailPelanggan.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<title>Email Selection</title>
{% endblock meta %}

{% block content %}

<div style="text-align: justify;"> 
    <h1>Pilih Email Pengguna</h1>
        <form action="{% url 'biru:create' %}" method="POST">
            {% csrf_token %}
            <label for="fname">Email</label>
            <input type="text" name="email" id="cars" list="cityname">
            <datalist id="cityname">
                {% for dum in dummy %}
                    <option value= {{ dum.0 }}>{{ dum.0 }}</option>
                {% endfor %}
            </datalist>
            <br>
            <br>
            <button type="submit" value="Submit">Submit</button>
        </form>
</div>

{% endblock content %}

biru/templates/kurir.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<title>Read Transaksi TOPUP DPAY Kurir</title>
{% endblock meta %}

{% block content %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">Email</th>
        <th scope="col">Tanggal</th>
        <th scope="col">Nominal</th>
      </tr>
    </thead>
    <tbody>
      {% for dum in dummy %}
      <tr>
          <td>{{ dum.0 }}</td>
          <td>{{ dum.1 | date:'Y/m/d H:i:s' }}</td>
          <td>{{ dum.2 }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock content %}

biru/templates/pelanggan.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/update_laundry.css' %}">
<title>Transaksi TOPUP DPAY Staff</title>
{% endblock meta %}

{% block content %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Email</th>
        <th scope="col">Tanggal</th>
        <th scope="col">Nominal</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
        {% for dum in dummy %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ dum.0 }}</td>
            <td>{{ dum.1 | date:'Y/m/d H:i:s'  }}</td>
            <td>{{ dum.2 }}</td>
            <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button class="btn btn-primary update_{{ forloop.counter }}_open" onclick="pop_up(this);" data-id="{{ forloop.counter }}" >Update</button>
                    <button class="btn btn-danger delete_{{ forloop.counter }}_open" onclick="popup_delete(this);" data-id="{{ forloop.counter }}">Delete</button>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>

  {% for dum in dummy %}
  <section id="update_{{ forloop.counter }}" class="hide">
    {% include "update.html" with dum=dum num=forloop.counter %}
  </section>
  <section id="delete_{{ forloop.counter }}" class="hide">
    <h3>Apakah kamu yakin ingin menghapus ini?</h3>
    <div class="d-flex justify-content-end">
      <form action="{% url 'biru:delete' %}" method="POST">
        {% csrf_token %}
        <input name="tanggal" style="display: none;" value="{{ dum.1 | date:'Y/m/d H:i:s' }}">
        <button type="submit" class="btn btn-primary">Ya</button>
      </form>
      <button class="delete_{{ forloop.counter }}_close">Tidak</button>
    </div>
  </section>
  {% endfor %}

<script>
  function popup_delete(el) {
    var s = el.getAttribute('data-id');
    $(`#delete_${s}`).popup({
        pagecontainer: '#page',
        transition: 'all 300ms ease-in-out'
    });
}

</script>
{% endblock content %}

{% block jsfile %}
<script src="https://cdn.jsdelivr.net/gh/vast-engineering/jquery-popup-overlay@2/jquery.popupoverlay.min.js"></script>
<script src="{% static 'js/u_list_laundry.js' %}"></script>
{% endblock jsfile %}

biru/templates/staff.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/update_laundry.css' %}">
<title>Transaksi TOPUP DPAY Staff</title>
{% endblock meta %}

{% block content %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Email</th>
        <th scope="col">Tanggal</th>
        <th scope="col">Nominal</th>
        {% if request.session.user_type != "Kurir" %}
                <th scope="col">Action</th>   
        {% endif %}
      </tr>
    </thead>
    <tbody>
        {% for dum in dummy %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ dum.0 }}</td>
            <td>{{ dum.1 | date:'Y/m/d H:i:s' }}</td>
            <td>{{ dum.2 }}</td>
            {% if request.session.user_type != "Kurir" %}
            <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button class="btn btn-primary update_{{ forloop.counter }}_open" onclick="pop_up(this);" data-id="{{ forloop.counter }}" >Update</button>
                    <button class="btn btn-danger delete_{{ forloop.counter }}_open" onclick="popup_delete(this);" data-id="{{ forloop.counter }}">Delete</button>
                </div>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
  </table>

  {% if request.session.user_type == "Staf" %}
  {% for dum in dummy %}
  <section id="update_{{ forloop.counter }}" class="hide">
    {% include "update.html" with dum=dum num=forloop.counter %}
  </section>
  <section id="delete_{{ forloop.counter }}" class="hide">
    <h3>Apakah kamu yakin ingin menghapus ini?</h3>
    <div class="d-flex justify-content-end">
      <form action="{% url 'biru:delete' %}" method="POST">
        {% csrf_token %}
        <input name="tanggal" style="display: none;" value="{{ dum.1 | date:'Y-m-d H:i:s' }}">
        <button type="submit" class="btn btn-primary">Ya</button>
      </form>
      <button class="delete_{{ forloop.counter }}_close">Tidak</button>
    </div>
  </section>
  {% endfor %}
  {% endif %}

<script>
  function popup_delete(el) {
    var s = el.getAttribute('data-id');
    $(`#delete_${s}`).popup({
        pagecontainer: '#page',
        transition: 'all 300ms ease-in-out'
    });
}

</script>
{% endblock content %}

{% block jsfile %}
<script src="https://cdn.jsdelivr.net/gh/vast-engineering/jquery-popup-overlay@2/jquery.popupoverlay.min.js"></script>
<script src="{% static 'js/u_list_laundry.js' %}"></script>
{% endblock jsfile %}

biru/templates/status.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<title>Read Status</title>
{% endblock meta %}

{% block content %}

<table class="table">
    <thead>
      <tr>
        <th scope="col">kode</th>
        <th scope="col">nama</th>
      </tr>
    </thead>
    <tbody>
        {% for dum in dummy %}
          <tr>
              <td>{{ dum.0 }}</td>
              <td>{{ dum.1|capfirst }}</td>
            </tr>
        {% endfor %}
    </tbody>
  </table>
{% endblock content %}

biru/templates/update.html
<form action="{% url 'biru:update' %}" method="POST" class="formie_{{ num }}">
    {% csrf_token %}
    <div class="form-group">
        <label for="user-email">Email address</label>
        <input type="email" name="email" class="form-control" id="user-email" style="text-align: start;" value="{{ dum.0 }}" readonly>
    </div>
    <div class="form-group d-flex flex-row">
        <div class="form-group d-flex flex-row">
                <label for="date">Tanggal</label>
                <input type="text" id="date" name="date" class="form-control" value="{{ dum.1 | date:'Y/m/d H:i:s' }}" readonly>
        </div>
    </div>
    <div class="d-flex flex-row justify-content-between">
        <div class="form-group">
            <label for="user-item">Nominal</label>
            <input id="user-nominal" name="nominal" class="form-control" value="{{ dum.2 }}">
        </div>
    </div>
    <button id="b_{{ num }}" type="submit" style="opacity: 0; height: 1px;"></button>
</form>
<div class="d-flex justify-content-end">
    <button class="btn btn-primary" onclick="popup_button(this);" data-button="{{ num }}" >Update</button>
</div>

<section id="yakin_{{ num }}" class="hide">
        <h2>Apakah kamu yakin?</h2>
        <button type="submit" class="btn btn-primary" data-id="{{ num }}" onclick="submit_form(this);">Ya</button>
        <button id="yakin_{{ num }}_close">Tidak</button>
</section>