biru/urls.py
from django.urls import path

from . import views

app_name = 'biru'

urlpatterns = [
    path('', views.home, name='home'),
    path('qstaff', views.qstaff, name='qstaff'),
    path('qpelanggan', views.qpelanggan, name='qpelanggan'),
    path('qkurir', views.qkurir, name='qkurir'),
    path('staff', views.staff, name='staff'),
    path('update', views.update, name='update'),
    path('delete', views.delete, name='delete'),
    path('kurir', views.kurir, name='kurir'),
    path('create', views.create, name='create'),
    path('status', views.status, name='status'),
    path('pilih', views.pilihEmail, name='pilih'),
]

hijau/urls.py
from django.urls import path

from . import views

app_name = 'hijau'

urlpatterns = [
    path('laundry/create/', views.home, name='home'),
    path('laundry/list/', views.read_daftar_laundry, name='read_laundry'),
    path('laundry/update/', views.update_laundry, name='update_laundry'),
    path('laundry/delete/', views.delete_laundry, name='delete_laundry'),
    path('item/create', views.create_item, name='create_item'),
    path('item/list', views.read_item, name='read_item')
]

kuning/urls.py
from django.urls import path

from . import views

app_name = 'kuning'

urlpatterns = [
    path('', views.home, name='home'),
    path('read_tarif', views.read_tarif, name='read_tarif'),
    path('create_tarif', views.create_tarif, name='create_tarif'),
    path('update_tarif/<slug:kode_update>', views.update_tarif, name='update_tarif'),
    path('delete_tarif/<slug:kode_delete>', views.delete_tarif, name='delete_tarif'),
    path('read_profil', views.read_profil, name='read_profil'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('register/kurir', views.register_kurir, name='register_kurir'),
    path('register/staf', views.register_staf, name='register_staf'),
    path('register/pelanggan', views.register_pelanggan, name='register_pelanggan'),
]

merah/urls.py
from django.urls import path

from . import views

app_name = 'merah'

urlpatterns = [
    path('', views.home, name='home'),
    path('testimoni/rud', views.rud_testimoni, name='rud_testimoni'),
    path('layanan/ru', views.ru_layanan, name='ru_layanan'),
    path('testimoni/create', views.createtestimoni, name='createtestimoni'),
    path('testimoni/update', views.updatetestimoni, name='updatetestimoni'),
    path('layanan/update', views.updatelayanan, name='updatelayanan'),
]

project_tk2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('merah/', include('merah.urls')),
    path('kuning/', include('kuning.urls')),
    path('hijau/', include('hijau.urls')),
    path('biru/', include('biru.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap 4.5 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Font Awesome -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/e76dc76644.js" crossorigin="anonymous"></script>
  
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% if request.session.is_login %}
    <header>
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Halo, {{ request.session.nama_lengkap }}</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'kuning:read_profil' %}" class="nav-link">Profil</a>
        </li>

        <!-- Transaksi Laundry -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Transaksi Laundry
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if request.session.user_type == "Staf" %}
              <a class="dropdown-item" href="#">Buat Transaksi Laundry</a>
              {% endif %}
              <a class="dropdown-item" href="#">Daftar Transaksi Laundry</a>
            </div>
        </li>

        <!-- Transaksi TOP UP DPAY -->
        {% if request.session.user_type != "Kurir" %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarTopUP" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Transaksi TOP UP DPAY
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarTopUP">
              {% if request.session.user_type == "Staf" %}
              <a class="dropdown-item" href="{% url 'biru:create' %}">Buat Transaksi TOP UP</a>
              <a class="dropdown-item" href="{% url 'biru:staff' %}">Daftar Transaksi TOP UP</a>
              {% else %}
              <a class="dropdown-item" href="{% url 'biru:staff' %}">Daftar Transaksi TOP UP</a>
              {% endif %}
            </div>
        </li>
        {% endif %}

        <!-- Daftar Laundry -->
        {% if request.session.user_type == "Staf" %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDaftar" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Daftar Laundry
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDaftar">
              {% if request.session.user_type == "Staf" %}
              <a class="dropdown-item" href="{% url 'hijau:home' %}">Buat Daftar Laundry</a>
              {% endif %}
              <a class="dropdown-item" href="{% url 'hijau:read_laundry' %}">Daftar Laundry</a>
            </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url 'hijau:read_laundry' %}" class="nav-link">Daftar Laundry</a>
        </li>
        {% endif %}


        {% if request.session.user_type != "Kurir" %}
        <li class="nav-item">
          <a href="#" class="nav-link">Tarif</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a href="{% url 'merah:rud_testimoni' %}" class="nav-link">Testimoni</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">Status Transaksi</a>
        </li>
        <li class="nav-item"><a href="{% url 'main:logout' %}" class="nav-link">Logout</a></li>
      </ul>
    </header>
  {% endif %}
  {% block content %}
  {% endblock content %}
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="crossorigin="anonymous"></script>  
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  {% block jsfile %}
  {% endblock jsfile %}
</body>

</html>