biru/urls.py
from django.urls import path

from . import views

app_name = 'biru'

urlpatterns = [
    path('', views.home, name='home'),
    path('qstaff', views.qstaff, name='qstaff'),
    path('qpelanggan', views.qpelanggan, name='qpelanggan'),
    path('qkurir', views.qkurir, name='qkurir'),
    path('staff', views.staff, name='staff'),
    path('update', views.update, name='update'),
    path('delete', views.delete, name='delete'),
    path('kurir', views.kurir, name='kurir'),
    path('create', views.create, name='create'),
    path('status', views.status, name='status'),
    path('pilih', views.pilihEmail, name='pilih'),
]

hijau/urls.py
from django.urls import path

from . import views

app_name = 'hijau'

urlpatterns = [
    path('laundry/create/', views.home, name='home'),
    path('laundry/list/', views.read_daftar_laundry, name='read_laundry'),
    path('laundry/update/', views.update_laundry, name='update_laundry'),
    path('laundry/delete/', views.delete_laundry, name='delete_laundry'),
    path('item/create', views.create_item, name='create_item'),
    path('item/list', views.read_item, name='read_item')
]

project_tk2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('merah/', include('merah.urls')),
    path('kuning/', include('kuning.urls')),
    path('hijau/', include('hijau.urls')),
    path('biru/', include('biru.urls')),
]

hijau/models.py
from django.db import models

# Create your models here.

hijau/forms.py
from django import forms
from django.db import connection
class CreateListLaundryForm(forms.Form):
    att = {'class':'form-control'}
    email = forms.EmailField(widget=forms.EmailInput(attrs=att))
    tanggal_transaksi = forms.DateTimeField(input_formats=["%Y/%m/%d %H:%M:%S"], widget=forms.Select(attrs=att, choices=[]))
    jumlah_item = forms.IntegerField(min_value=0, widget=forms.NumberInput(attrs=att))
    kode_item = forms.ChoiceField(choices=[], widget=forms.Select(attrs=att, choices=[]))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        with connection.cursor() as cursor:
            cursor.execute('SELECT kode FROM item')
            lst = [ (i[0],i[0]) for i in cursor.fetchall() ]
            self.fields['kode_item'].choices = lst
            self.fields['kode_item'].widget.choices = lst

    

hijau/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.core.paginator import Paginator, PageNotAnInteger
from django.db import connection
# from django.utils.timezone import localtime
# import datetime

from .forms import CreateListLaundryForm


import math;


# Create your views here.

def home(request):
    if 'is_login' in request.session:
        context = {
            'form' : CreateListLaundryForm(),
            'hasSubmitBefore' : False
        }
        if request.is_ajax():
            keyword = request.POST.get('email')
            context = {}
            with connection.cursor() as cursor:
                cursor.execute(f"SELECT tanggal FROM transaksi_laundry WHERE email='{keyword}'")
                context['tgl'] = cursor.fetchall()
            html = render_to_string(
                template_name='daftar_laundry/list_tanggal.html',
                context = context
            )

            return JsonResponse(data={'template':html})
        if request.method == 'POST':
            form = CreateListLaundryForm(request.POST)
            if form.is_valid():
                email = form.cleaned_data['email']
                tgl = form.cleaned_data['tanggal_transaksi']
                tgl = tgl.replace(tzinfo=None)
                jumlah_item = form.cleaned_data['jumlah_item']
                kode_item = form.cleaned_data['kode_item']
                # hitung jumlah daftar laundry yg ada
                with connection.cursor() as cursor:
                    cursor.execute('SELECT COUNT(*) FROM daftar_laundry')
                    no_urut =  cursor.fetchone()[0] + 1
                query = f'INSERT INTO "daftar_laundry" VALUES  (\'{email}\', \'{tgl}\', {no_urut}, {jumlah_item}, \'{kode_item}\')'
                with connection.cursor() as cursor:
                    cursor.execute( query )
                context['hasSubmitBefore'] = True
                messages.success(request, 'Daftar laundry berhasil dibuat.')

        return render(request, 'daftar_laundry/create_list_laundry.html', context)
    return redirect('main:login_view')

def read_daftar_laundry(request):
    if 'is_login' in request.session :
        # jika bukan kurir maka dapat read daftar laundry
        if request.session['user_type'] != 'Kurir':
            with connection.cursor() as cursor:
                # ambil semua daftar laundry jika staf,
                # jika pelanggan, maka ambil berdasarkan email
                if request.session['user_type'] == 'Staf':
                    cursor.execute('SELECT * FROM daftar_laundry ORDER BY no_urut ASC')
                elif request.session['user_type'] == 'Pelanggan':
                    email = request.session['email'].replace('PELANGGAN', '')
                    cursor.execute(f'SELECT * FROM daftar_laundry WHERE email=\'{email}\' ORDER BY no_urut ASC')
                lists = cursor.fetchall()
                cursor.execute('SELECT kode FROM item')
                codes = cursor.fetchall()

            paginator = Paginator(lists, 5)
            page = request.GET.get('page')

            try:
                p = paginator.page(page)
            except PageNotAnInteger:
                p = paginator.page(1)
            email = request.session['email'].replace(request.session['user_type'].upper(), '')
            context = {
                'kode_list': [code[0] for code in codes],
                'isStaff' : request.session['user_type'] == 'Staf',
                'dummy' : p,
                'pelanggan_email' : email
            }
            if not context['isStaff']:
                c = lambda x : len([i for i in lists if i[0]==x])
                context['num_pesanan'] = c(context['pelanggan_email'])
                context['range'] = range(1,math.ceil(context['num_pesanan']/5+1 ))
            return render(request, 'daftar_laundry/read_list_laundry.html', context)
        return redirect('kuning:read_profil')
    return redirect('/login/')

def update_laundry(request):
    if request.method == 'POST':
        no_urut = request.POST['no_urut']
        j_item = request.POST['jumlah_item']
        k_item = request.POST['kode_item']
        # update daftar laundry
        with connection.cursor() as cursor:
            cursor.execute(f"UPDATE daftar_laundry SET jumlah_item={j_item}, kode_item='{k_item}' \
                            WHERE no_urut={no_urut}")
        return redirect('hijau:read_laundry')


def delete_laundry(request):
    if request.method == 'POST':
        no_urut = request.POST['no_urut']
        query = f'DELETE FROM daftar_laundry WHERE no_urut={no_urut}'
        with connection.cursor() as cursor:
            # dapatkan jumlah row di daftar_laundry
            cursor.execute('SELECT COUNT(*) FROM daftar_laundry')
            max = cursor.fetchone()[0]
            # jalankan query delete
            cursor.execute(query)

            # update no_urut dari data yg dihapus sampai data terakhir
            for i in range(no_urut, max):
                cursor.execute(f'UPDATE daftar_laundry SET no_urut=no_urut-1 WHERE no_urut={no_urut+1}')
        return redirect('hijau:read_laundry')

def read_item(request):
    if 'is_login' in request.session :
        with connection.cursor() as cursor:
            cursor.execute('SELECT * FROM item')
            dummy = cursor.fetchall()
        context = {
            'dummy' : dummy
        }
        return render(request, 'item/read_item.html', context)
    return redirect('main:login_view')

def create_item(request):
    if 'is_login' in request.session:
        if request.session['user_type'] == 'Staf':
            if request.method == 'POST':
                query = f"INSERT INTO item VALUES ('{request.POST['kode_item']}','{request.POST['nama_item']}')"
                with connection.cursor() as cursor:
                    cursor.execute( query )
            return render(request, 'item/create_item.html')
        return redirect('kuning:read_profil')
    return redirect('/login/')

hijau/templates/daftar_laundry/create_list_laundry.html
{% extends "base.html" %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/create_laundry.css' %}">
{% endblock meta %}

{% block content %}
<div class="create-list-form">
  <h2>CREATE DAFTAR LAUNDRY</h2>
  <form action="{% url 'hijau:home' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_email">{{ form.email.label }}</label>
      {{ form.email }}
    </div>
    <div class="form-group">
      <label for="id_tanggal_transaksi">{{ form.tanggal_transaksi.label }}</label>
      {{ form.tanggal_transaksi }}
    </div>
    <div class="form-group">
      <label for="id_jumlah_item">{{ form.jumlah_item.label }}</label>
      {{ form.jumlah_item }}
    </div>
    <div class="form-group">
      <label for="id_kode_item">{{ form.kode_item.label }}</label>
      {{ form.kode_item }}
    </div>
    <div class="d-flex justify-content-end">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
</div>
{% if hasSubmitBefore %}
  {% if messages %}
    {% for m in messages  %}
    {{ m }}
    {% endfor %}
  {% endif %}
{% endif %}
{% endblock content %}

{% block jsfile %}
<script id="csrf" type="application/json">{"hello": "{{ csrf_token }}"}</script>
<script src="{% static 'js/tanggal_ajax.js' %}"></script>
{% endblock jsfile %}

hijau/templates/daftar_laundry/list_tanggal.html
<select name="tanggal_transaksi" id="id_tanggal_transaksi" class="form-control">
    {% for i in tgl %}
      <option value="{{ i.0 | date:'Y/m/d H:i:s' }}">{{ i.0 | date:'Y/m/d H:i:s' }}</option>
    {% endfor %}
</select>

hijau/templates/daftar_laundry/read_list_laundry.html
{% extends "base.html" %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/update_laundry.css' %}">
{% endblock meta %}

{% block content %}
<div id="page">

    <table class="table" style="border-bottom: 1px solid #dee2e6;">
        <thead class="thead-light">
            <tr>
                <th scope="col">No</th>
                <th scope="col">Email</th>
                <th scope="col">Tanggal Transaksi</th>
                <th scope="col">No Urut</th>
                <th scope="col">Jumlah Item</th>
                <th scope="col">Kode Item</th>
                {% if isStaff %}
                <th scope="col">Action</th>
                  
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for dum in dummy %}
              <tr>
                {% if isStaff is False %}
                  {% if dum.0 == pelanggan_email %}
                    <th scope="row">{{ dummy.start_index|add:"-1"|add:forloop.counter }}</th>
                    <td>{{ dum.0 }}</td>
                    <td>{{ dum.1 | date:"d/m/Y" }}</td>
                    <td>{{ dum.2 }}</td>
                    <td>{{ dum.3 }}</td>
                    <td>{{ dum.4 }}</td>
                    
                  {% endif %}
                {% else %}
                <th scope="row">{{ dummy.start_index|add:"-1"|add:forloop.counter }}</th>
                  <td>{{ dum.0 }}</td>
                  <td>{{ dum.1 | date:"d/m/Y" }}</td>
                  <td>{{ dum.2 }}</td>
                  <td>{{ dum.3 }}</td>
                  <td>{{ dum.4 }}</td>
                {% endif %}
                  {% if isStaff %}
                  <td>
                      <button class="btn btn-primary update_{{ forloop.counter }}_open" onclick="pop_up(this);" data-id="{{ forloop.counter }}" >Update</button>
                      <button class="btn btn-primary delete_{{ forloop.counter }}_open" onclick="popup_delete(this);" data-id="{{ forloop.counter }}">Delete</button>
                  </td>
                  {% endif %}
               </tr>
               {% endfor %}
              </tbody>
          </table>
</div>

<!-- Pop Up Form untuk Update -->
  {% if isStaff %}
  {% for dum in dummy %}
  <section id="update_{{ forloop.counter }}" class="hide">
    {% include "daftar_laundry/update_list_laundry.html" with dum=dum kode=kode_list num=forloop.counter total=dummy %}
  </section>
  <section id="delete_{{ forloop.counter }}" class="hide">
    <h3>Apakah kamu yakin ingin menghapus ini?</h3>
    <div class="d-flex justify-content-end">
      <form action="{% url 'hijau:delete_laundry' %}" method="post">
        {% csrf_token %}
        <input type="number" name="no_urut" style="display: none;" value="{{ dum.2 }}">
        <button type="submit" class="btn btn-primary">Ya</button>
      </form>
      <button class="delete_{{ forloop.counter }}_close">Tidak</button>
    </div>
  </section>
  {% endfor %}

  {% endif %}
        
        <div class="d-flex justify-content-center">
            <ul class="pagination">
              {% if isStaff %}
              {% for i in dummy.paginator.page_range %}
                {% if dummy.number == i %}
                  <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                  <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
              {% endfor %}
              
              {% else %}
              {% for i in range %}
              {% if dummy.number == i %}
              <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
              {% endfor %}
              {% endif %}
            </ul>
        </div>
{% endblock content %}


{% block jsfile %}
<script src="https://cdn.jsdelivr.net/gh/vast-engineering/jquery-popup-overlay@2/jquery.popupoverlay.min.js"></script>
<script src="{% static 'js/u_list_laundry.js' %}"></script>
{% endblock jsfile %}

hijau/templates/daftar_laundry/update_list_laundry.html
<form action="{% url 'hijau:update_laundry' %}" method="POST" class="formie_{{ num }}">
    {% csrf_token %}
    <div class="form-group">
        <label for="user-email">Email address</label>
        <input type="email" name="email" class="form-control" id="user-email" style="text-align: start;" value="{{ dum.0 }}" readonly>
    </div>
    <div class="form-group d-flex flex-row">
        <div class="form-group d-flex flex-row">
                <label for="date">Tanggal</label>
                <input type="text" id="date" name="date" class="form-control" maxlength="2" min="1" value="{{ dum.1 | date:'d'  }}" readonly>
        </div>
        <div class="form-group d-flex flex-row">
        <label for="month">-</label>
        <input type="text" id="month" name="month" class="form-control" max="12" min="1" value="{{ dum.1 | date:'m' }}" readonly>
    </div>
    <div class="form-group d-flex flex-row">
        <label for="year">-</label>
        <input type="text" id="year" name="year" class="form-control" maxlength="4" min="2010" value="{{ dum.1 | date:'Y' }}" readonly>
    </div>
    </div>
    <div class="d-flex flex-row justify-content-between">
        <div class="form-group">
            <label for="user-urut">Nomor Urut</label>
            <input type="number" id="user-urut" name="no_urut" class="form-control" max="{{ total.paginator.count }}" min="1" value="{{ dum.2 }}">
        </div>
        <div class="form-group">
            <label for="user-item">Jumlah Item</label>
            <input type="number" id="user-item" name="jumlah_item" class="form-control" min="1" value="{{ dum.3 }}">
        </div>
        <div class="form-group">
            <label for="user-kode">Kode Item</label>
            <select class="form-control" id="user-kode" name="kode_item">
                {% for i in kode  %}
                    {% if i == dum.4 %}
                        <option selected>{{ i }}</option>  
                    {% else %}
                        <option >{{ i }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </div>
    </div>
    <button id="b_{{ num }}" type="submit" style="opacity: 0; height: 1px;"></button>
</form>
<div class="d-flex justify-content-end">
    <button class="btn btn-primary" onclick="popup_button(this);" data-button="{{ num }}" >Update</button>
</div>

<section id="yakin_{{ num }}" class="hide">
        <h2>Apakah kamu yakin?</h2>
        <button type="submit" class="btn btn-primary" data-id="{{ num }}" onclick="submit_form(this);">Ya</button>
        <button id="yakin_{{ num }}_close">Tidak</button>
</section>